receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
#  jaeger:
#    endpoint: jaeger-all-in-one:4317
#    tls:
#      insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]